<div class="container">
        <section class="section">
            <h2>Our Team</h2>
            <p>Our team at Furni is a diverse group of talented individuals who share a passion for design and customer satisfaction. From our creative designers to our customer support specialists, each member of our team plays a crucial role in delivering the best furniture shopping experience to you. Get to know the people who make Furni exceptional.</p>
        </section>
    </div>